default:
    image: node:latest

build-job:
    stage: build
    script:
        - echo "Hello, GitLab"
        - yarn
        - yarn build

deploy-job:
    stage: deploy
    script:
        - echo "Deploy"