version: "3.0"
services:
   web:
     image: hello-brunch      
     build: .
     ports:
       - "80:80"
     logging:
       driver: fluentd
       options:
         fluentd-address: "10.250.10.2:24224"
