version: "3.0"
services:
   web:
     image: hello-brunch      
     build: .
     ports:
       - "8080:80"
     logging:
       driver: loki
       options:
         loki-url: "http://10.250.10.2:3100/loki/api/v1/push"
