version: "3.0"
services:
   web:
     image: hello-brunch      
     build: .
     ports:
       - "8080:80"
     logging:
       driver: syslog
       options:
         syslog-address: "tcp://10.250.10.2:5000"
